POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
        "title": "Hello World",
        "author": "Harshit Katyal",
        "url": "https://helloWorld.com/",
        "likes": "4"
}